### ISSUE TITLE
用Swift package manager导入后编译错误

### ISSUE THREAD

**Issue by Asura19** [KittenYang/Longinus#10]
<img width="1492" alt="截屏2020-09-20 下午2 52 34" src="https://user-images.githubusercontent.com/13399701/93705558-fd121e80-fb50-11ea-96cd-bb10f0fc3d23.png">
请问还需要再导入什么框架吗

**Comment by KittenYang** [comment]
1.1.13 已修复，更新一下 SPM 试试

**Comment by Asura19** [comment]
已修复, 感谢
