### ISSUE TITLE
Struct 'LGImage' does not exist in module 'Longinus'

### ISSUE THREAD

**Issue by RobotAmiee** [KittenYang/Longinus#15]
When using Longinus with SPM in Xcode 12 and import LGImage with`import struct Longinus.LGImage`, Xcode shows build error "Struct 'LGImage' does not exist in module 'Longinus'".

**Comment by KittenYang** [comment]
Fixed in https://github.com/KittenYang/Longinus/pull/16, please update your SPM to check it.
```swift 
import LonginusSwiftUI
```
