### ISSUE TITLE
Error while creating Archive

### ISSUE THREAD

**Issue by kebrick** [KittenYang/Longinus#21]
Version: 1.1.16
Perhaps you know the solution to the problem.

![image](https://user-images.githubusercontent.com/25265239/138567628-70985a31-b3bd-4ae5-b21a-fd4012bd511d.png)

**Comment by Zrzzzz** [comment]
I solved it by appending this code in Podfile.
```
post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
```

**Comment by KittenYang** [comment]
@Zrzzzz pr is welcome!

**Comment by Zrzzzz** [comment]
> @Zrzzzz pr is welcome!

However I'm not familier with Cocoapods, just solved it by adding code in my project Podfile🤣

**Comment by kebrick** [comment]
> > @Zrzzzzпр приветствуется!
> 
> Однако я не знаком с Cocoapods, просто решил это, добавив код в свой проект Podfile.🤣

thx
