### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by metin-atalay** [KittenYang/Longinus#28]
Hi Dear,
Can you add the tvOS version in your package? We use this nice library in appleTV side.

like below
<img width="640" alt="image" src="https://user-images.githubusercontent.com/9380512/185420606-d0db7556-5b8d-4616-bd60-fd3a9b89e351.png">

**Comment by KittenYang** [comment]
sorry ,there is not in my plan. but your pr is welcome!

**Comment by metin-atalay** [comment]
Hi @KittenYang ,

Thanks for the reply and the great project :) 

We removed the Longinus from our project (our project is very big like **Netflix**, and another project like **SoundCloud**). There are lots of reasons why we do this.
First, Benchmark tests are not correct because we chose KingFisher after the Longinus so our project, images are loaded very fast and the production bug is fixed (You can see I opened another issue #30  ).
