### ISSUE TITLE
 Error when archive as SPM

### ISSUE THREAD

**Issue by symayeter-zz** [KittenYang/Longinus#29]
We get following error when  added it as SPM. Kindly advice.

<img width="349" alt="Screenshot 2022-09-01 at 16 36 57" src="https://user-images.githubusercontent.com/17738951/187927781-9f63e2a0-d37f-4e58-b07b-c0820e626581.png">

**Comment by KittenYang** [comment]
I tested on Xcode 14 and it's no worry, pls try latest version.
